# Generated by Django 4.2.13 on 2026-04-06 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('officer', 'Agronomist / Outreach Officer'), ('researcher', 'Researcher')], default='farmer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('optimal_n', models.FloatField(help_text='Optimal Nitrogen (kg/ha)')),
                ('optimal_p', models.FloatField(help_text='Optimal Phosphorus (kg/ha)')),
                ('optimal_k', models.FloatField(help_text='Optimal Potassium (kg/ha)')),
                ('optimal_ph_min', models.FloatField(default=5.5)),
                ('optimal_ph_max', models.FloatField(default=7.5)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Temperature in °C')),
                ('humidity', models.FloatField(help_text='Relative humidity (%)')),
                ('rainfall', models.FloatField(help_text='Rainfall in mm')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField(help_text='Nitrogen content in kg/ha')),
                ('phosphorus', models.FloatField(help_text='Phosphorus content in kg/ha')),
                ('potassium', models.FloatField(help_text='Potassium content in kg/ha')),
                ('ph', models.FloatField(help_text='Soil pH (0–14)')),
                ('moisture', models.FloatField(help_text='Soil moisture percentage')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(help_text='Model confidence 0.0–1.0')),
                ('explanation_text', models.TextField(help_text='Human-readable SHAP-based explanation')),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='api.crop')),
                ('soil_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.soildata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
                ('weather_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.weatherdata')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
