/**
 * HistoryTable — paginated list of past recommendations
 */
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { recommendationService } from "../services/api";
import { toast } from "react-toastify";

export default function HistoryTable() {
  const [data, setData] = useState([]);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [loading, setLoading] = useState(true);

  const downloadHistoryReport = () => {
    const now = new Date();
    const generatedDate = now.toLocaleDateString('en-IN', {
      day: 'numeric', month: 'long', year: 'numeric',
      hour: '2-digit', minute: '2-digit',
    });
    const fileDate = now.toISOString().slice(0, 10);
    const escapeHTML = (text) =>
      String(text ?? "")
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");

    const rows = data
      .map((rec) => {
        const date = new Date(rec.timestamp).toLocaleDateString();
        const cropName = escapeHTML(rec.crop?.name ?? rec.crop_name ?? "—");
        const explanation = escapeHTML(rec.explanation_text ?? rec.explanation ?? "");
        const confidence = Math.round((rec.confidence_score ?? rec.confidence ?? 0) * 100);
        const confidenceColor =
          confidence >= 80 ? '#16a34a' : confidence >= 60 ? '#ca8a04' : '#dc2626';

        return `
          <tr>
            <td style="padding:12px;border:1px solid #d1d5db;">${date}</td>
            <td style="padding:12px;border:1px solid #d1d5db;">${cropName}</td>
            <td style="padding:12px;border:1px solid #d1d5db;color:${confidenceColor};font-weight:700;">${confidence}%</td>
            <td style="padding:12px;border:1px solid #d1d5db;">${explanation}</td>
          </tr>`;
      })
      .join('');

    const reportHTML = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8" />
        <title>CropAI — Recommendation History Report</title>
        <style>
          body { font-family: Arial, sans-serif; max-width: 1000px; margin: 40px auto; color: #111827; line-height: 1.6; }
          .header { text-align: center; margin-bottom: 30px; }
          .header h1 { margin: 0; font-size: 28px; color: #16a34a; }
          .header p { margin: 6px 0; color: #4b5563; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th, td { border: 1px solid #d1d5db; padding: 12px 14px; text-align: left; }
          th { background: #f9fafb; color: #111827; }
          tr:nth-child(even) { background: #f8fafc; }
          .footer { margin-top: 30px; font-size: 12px; color: #6b7280; text-align: center; }
          @media print { body { margin: 20px; } table { page-break-inside: auto; } tr { page-break-inside: avoid; page-break-after: auto; } }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>CropAI — Recommendation History Report</h1>
          <p>Generated on ${generatedDate}</p>
          <p>Total recommendations: ${data.length}</p>
        </div>
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Crop</th>
              <th>Confidence</th>
              <th>Explanation Summary</th>
            </tr>
          </thead>
          <tbody>
            ${rows}
          </tbody>
        </table>
        <div class="footer">Generated by CropAI</div>
      </body>
      </html>
    `;

    const blob = new Blob([reportHTML], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `CropAI_History_Report_${fileDate}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    toast.success('✅ History report downloaded successfully!');
  };

  useEffect(() => {
    setLoading(true);
    recommendationService
      .getHistory(page)
      .then(({ data: res }) => {
        setData(res.results ?? res);
        if (res.count) setTotalPages(Math.ceil(res.count / 20));
      })
      .catch(() => toast.error("Failed to load history"))
      .finally(() => setLoading(false));
  }, [page]);

  if (loading) {
    return (
      <div className="card flex justify-center py-12 text-gray-400">
        Loading history…
      </div>
    );
  }

  if (!data.length) {
    return (
      <div className="card text-center py-12 text-gray-500">
        No recommendations yet.{" "}
        <Link to="/" className="text-primary-600 underline">
          Get your first one!
        </Link>
      </div>
    );
  }

  return (
    <div className="card overflow-x-auto">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 mb-4">
        <div className="text-sm text-gray-500">Showing {data.length} recommendations</div>
        <button
          onClick={downloadHistoryReport}
          className="border border-green-600 text-green-600 rounded-lg px-5 py-2 font-semibold hover:bg-green-50 transition"
        >
          ⬇️ Download History Report
        </button>
      </div>
      <table className="w-full text-sm">
        <thead>
          <tr className="text-left text-gray-500 border-b border-gray-100">
            <th className="pb-3 font-medium">Date</th>
            <th className="pb-3 font-medium">Crop</th>
            <th className="pb-3 font-medium">Confidence</th>
            <th className="pb-3 font-medium">Summary</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-gray-50">
          {data.map((rec) => (
            <tr key={rec.id} className="hover:bg-gray-50 transition">
              <td className="py-3 text-gray-500 whitespace-nowrap">
                {new Date(rec.timestamp).toLocaleDateString()}
              </td>
              <td className="py-3 font-semibold capitalize">
                {rec.crop?.name ?? "—"}
              </td>
              <td className="py-3">
                <span
                  className={`font-medium ${
                    rec.confidence_score >= 0.8
                      ? "text-green-600"
                      : rec.confidence_score >= 0.6
                      ? "text-yellow-600"
                      : "text-red-500"
                  }`}
                >
                  {Math.round(rec.confidence_score * 100)}%
                </span>
              </td>
              <td className="py-3 text-gray-600 truncate max-w-xs">
                {rec.explanation_text}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex justify-center items-center gap-3 mt-4 pt-4 border-t border-gray-100">
          <button
            onClick={() => setPage((p) => Math.max(1, p - 1))}
            disabled={page === 1}
            className="text-sm px-3 py-1 rounded border disabled:opacity-40"
          >
            ← Prev
          </button>
          <span className="text-sm text-gray-500">
            Page {page} of {totalPages}
          </span>
          <button
            onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
            disabled={page === totalPages}
            className="text-sm px-3 py-1 rounded border disabled:opacity-40"
          >
            Next →
          </button>
        </div>
      )}
    </div>
  );
}
